### ISSUE TITLE
Integrate Chat Pipeline with Whisper and Google Text-to-Speech

### ISSUE THREAD

**Issue by SaranDharshanSP** [SaranDharshanSP/Amrita-Sports-Management-System#3]
### Description  
Integrate the chat pipeline with **Whisper** for speech-to-text input and **Google Text-to-Speech** for generating audio responses.

### Suggested Fix  
1. Use **Whisper** to transcribe user speech input into text.  
2. Process the text through the chat pipeline (existing logic).  
3. Use **Google Text-to-Speech** to convert the response back into audio output.  

### Expected Outcome  
A seamless voice-based interaction system integrated into the chat pipeline.

**Comment by SaranDharshanSP** [comment]
Wrong issue

**Comment by DomoMKT** [comment]
you can find a reliable and high-quality solution for converting text to speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).
